# Друзья R {#friends_of_R}

ывава
ыва
ыва


## Рабочий процесс {#workflow}

...


## Контроль версий {#version_control}

...


## Латех {#latex}


...

## Маркдаун {#markdown}

...

## Воспроизводимые исследования {#reproducible_research}

...

## Написание своего пакета {#own_package}

...

## Вычисления в облаке {#cloud_computing}

...

## Презентации {#presentations}

...

## Про эту книжку {#this_book}


Разбить на большее количество глав!!!

Что-то убрать? чтобы была ещё одна книжка? :)


Общие принципы:

1. Неформальный стиль, на "ты"

2. Больше картинок. Лицензия?

3. Больше гипер-ссылок.

4. Буква `ё` обязательна.


Пакет `bookdown` с помощью которого написана эта книжка ещё немного сыроват. В процессе работы я обнаружил, что:

1. Порой помогает удаление промежуточных файлов и компиляция заново.

2. После неанглоязычного названия главы обязательно должна идти метка `{#label}`.

3. Каждый `.Rmd` файл содержит только одну главу. Глава обозначается заголовком первого уровня `#`.

4. Сослаться на главу или подраздел можно с помощью `\@ref(label)`. 

5. Сослаться на источник литературы можно с помощью `[@reference]`


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

6. Для создания `MOBI` книг:

```{bash, eval=FALSE}
brew update
brew cask install calibre
brew cask install kindlegen
```

В предисловии
```{yaml, eval=FALSE}
bookdown::kindlegen:
  epub: _book/r_manual.epub
```

ругается


или
```{yaml, eval=FALSE}
bookdown::calibre:
  input: _book/r_manual.epub
  output: _book/r_manual.mobi 
```

ругается


7. заставляем травис работать

Создаём новый токен на [github](https://github.com/settings/tokens): кликнуть по иконке, далее settings - token - generate new token.

```{bash, eval=FALSE}
sudo gem install travis
travis encrypt [token from githum]
```

Добавляем получившуюся закодированную строку в `.travis.yml`. Забавно, что похоже используется рандомный ключ для шифрования и поэтому зашифрованная строка каждый раз выходит разной.


Для быстрой компиляции добавляем в `.travis.yml` указание, что мы будем использовать готовые бинарные пакеты R:
```{bash, eval=FALSE}
r_binary_packages:
  - ggplot2
  - dplyr
  - rio
```





